#!/bin/bash

if  [ ! -f includes/libsecp256k1.a ]; then
echo Cloning and Building secp256k1 library...
cd ..
git clone https://github.com/ElementsProject/secp256k1-zkp.git
cd secp256k1-zkp
./autogen.sh
./configure --enable-endomorphism --enable-module-ecdh --enable-module-schnorr --enable-module-rangeproof --enable-experimental --enable-module_recovery
make
cp .libs/libsecp256k1.a ../SuperNET/includes/
cd ../SuperNET
fi

git pull
cd crypto777
./$1
cd ..
