#!/bin/bash
../agents/iguana coins/genbtcd.json &
sleep 5
../agents/iguana coins/genbtc.json &
sleep 5
../agents/iguana coins/gendoge.json &
sleep 5
../agents/iguana coins/gendgb.json &
sleep 5
../agents/iguana coins/gengmc.json &
sleep 5
../agents/iguana coins/genltc.json &
sleep 5
../agents/iguana coins/genmzc.json &
sleep 5
../agents/iguana coins/gensys.json &
sleep 5
../agents/iguana coins/genuno.json &
sleep 5
../agents/iguana coins/genzet.json &
sleep 5
../agents/iguana coins/genbtm.json &
sleep 5
../agents/iguana coins/gencarb.json &
sleep 5
../agents/iguana coins/genanc.json &
sleep 5
../agents/iguana coins/genfrk.json &
