#!/bin/bash
source passphrase
source ../coins
../../target/debug/mm2 "{\"ethnode\":\"http://195.201.0.6:8545\",\"netid\":9999,\"seednode\":\"10.100.0.2\",\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}"
