#!/bin/bash
source passphrase
source ../coins
/usr/sbin/rinetd
rm -rf DB
gdbserver :4444 ../../target/debug/mm2 "{\"netid\":9999,\"seednode\":\"10.100.0.2\",\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}"
