#!/bin/bash
../coins/basilisk/bet
../coins/basilisk/btc
../coins/basilisk/dex		
../coins/basilisk/jumblr
../coins/basilisk/mgw
../coins/basilisk/pangea
../coins/basilisk/shark
../coins/basilisk/bots
../coins/basilisk/crypto
../coins/basilisk/hodl	
../coins/basilisk/kmd
../coins/basilisk/mvp	
../coins/basilisk/revs	
../coins/basilisk/supernet

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"basilisk\",\"method\":\"paxfiats\"}"
