#!/bin/bash
myip=`cat myip.txt`
pkill iguana
../agents/iguana notary &
sleep 4
coins/gennotary
tests/addnotarys_7776
tests/getinfoN_7776
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"myipaddr\",\"ipaddr\":\"$myip\"}"
./wp_7776
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"SuperNET\",\"method\":\"activehandle\"}"
./btc_7776
./kmd_7776
curl --url "http://127.0.0.1:7776" --data "{\"agent\":\"iguana\",\"method\":\"addnode\",\"activecoin\":\"NOTARY\",\"ipaddr\":\"$myip\"}"
./dpow_7776
