#!/bin/bash
source passphrase
source ../coins
../../target/debug/mm2 "{\"ethnode\":\"http://195.201.0.6:8545\",\"netid\":9999,\"gui\":\"nogui\", \"profitmargin\":0.01, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}"
