#!/bin/bash

if [[ $# -eq 0 ]]; then
   git pull
   #cd iguana; ./m_android; cd ..
fi
echo "Compiling crypto777..."
$CC2 -c -O2 *.c jpeg/*.c jpeg/unix/*.c
rm -f ../agents/libcrypto777.a; $AR rcu ../agents/libcrypto777.a *.o
