#!/bin/bash
source passphrase
source coins
./stop
git pull;
cd ..; 
./m_mm;
pkill -15 marketmaker; 
./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}" &

