#!/bin/bash
source passphrase
source coins
pkill -15 marketmaker; 
git pull;
cd ..; 
./m_mm;
./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}/Library/Application\ Support\", \"passphrase\":\"$passphrase\", \"coins\":$coins}" &

