#!/bin/bash
source passphrase
source coins
pkill -15 marketmaker; 
git pull;
cd ..; 
./m_mm;
gdb -args ./marketmaker "{\"gui\":\"nogui\",\"client\":1, \"userhome\":\"/${HOME#"/"}\", \"passphrase\":\"$passphrase\", \"coins\":$coins}" 

