#!/bin/bash
source userpass
# this will only work for watchonly addresses that have been rescanned and with active coins
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"fundvalue\",\"address\":\"RLvRzAFMgyGXuUwgHLfT8c5PyJqVZFhuUi\",\"holdings\":[],\"divisor\":1400000}"
