#!/bin/bash
source userpass
echo "usage: ./secretaddresses 'passphrase'"

curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"secretaddresses\",\"num\":16,\"passphrase\":\"$1\"}"

