#!/bin/bash
source userpass
# this will only work for watchonly addresses that have been rescanned and with active coins
echo mshark
./mshark
echo hodl
./hodl
echo dex
./dex
echo jumblr
./jumblr
echo bots
./bots
echo supernet

curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"balances\",\"address\":\"RLVzC4tr9cNKvuw2z4m8KuMfZURwCehx55\"}"
echo supernet
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"fundvalue\",\"address\":\"RLVzC4tr9cNKvuw2z4m8KuMfZURwCehx55\",\"holdings\":[{\"coin\":\"zcash\",\"balance\":0.10000}, {\"coin\":\"syscoin\",\"balance\":20000000}, {\"coin\":\"bitcoin\",\"balance\":50}, {\"coin\":\"heat-ledger\",\"balance\":2323851 }, {\"coin\":\"vericoin\",\"balance\":2199368 }, {\"coin\":\"byteball\",\"balance\":4238}, {\"coin\":\"hush\",\"balance\":100000 }, {\"coin\":\"verus\",\"balance\":2650000}],\"divisor\":777777}"

