#!/bin/bash
source userpass
# this will only work for watchonly addresses that have been rescanned and with active coins
echo mshark
./mshark
echo hodl
./hodl
echo dex
./dex
echo jumblr
./jumblr
echo bots
./bots
echo supernet

curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"balances\",\"address\":\"RRyyejME7LRTuvdziWsXkAbSW1fdiohGwK\"}"
echo supernet
curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"fundvalue\",\"address\":\"RRyyejME7LRTuvdziWsXkAbSW1fdiohGwK\",\"holdings\":[{\"coin\":\"stratis\",\"balance\":1227800}, {\"coin\":\"zcash\",\"balance\":0.10000}, {\"coin\":\"syscoin\",\"balance\":20000000}, {\"coin\":\"bitcoin\",\"balance\":450}, {\"coin\":\"bitcoin-cash\",\"balance\":1500}, {\"coin\":\"heat-ledger\",\"balance\":2323851 }, {\"coin\":\"vericoin\",\"balance\":2199368 }, {\"coin\":\"byteball\",\"balance\":4238}, {\"coin\":\"hush\",\"balance\":100000 }, {\"coin\":\"verus\",\"balance\":1650000}],\"divisor\":777777}"

