#!/bin/bash

clear
echo ""
echo "
The encryptwallet RPC encrypts the wallet with a passphrase. 
This is only to enable encryption for the first time. After encryption is enabled, 
you will need to enter the passphrase to use private keys"
echo ""
echo ""

echo "Scenario: Test encryptwallet RPC with long passphrase]"
echo "Result:  Should Return status:locked"
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"encryptwallet\",\"passphrase\":\"This is a very long passphrase i set to test the encryptwallet rpc\"}"
echo ""
echo ""
