#!/bin/bash

echo ""
echo "

The getaccount RPC returns the name of the account associated with the given address.

Parameter #1—a Bitcoin address
Result—an account name"
echo ""
echo ""
echo "Dependencies:"
echo "Getaccountaddress RPC, use the address return by getaccountaddress RPC"
echo ""

echo "Scenario: Verify the valid account's name is returned"
echo "Expected: RPCtesting account name should be returned" 
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccount\",\"address\":\"RQ9mx8ZMc5TcrsjZ8HJmgGzGZcT1DEqM1K\"}"
echo ""


