#!/bin/bash

echo ""
echo "

The getaccount RPC returns the name of the account associated with the given address.

Parameter #1—a Bitcoin address
Result—an account name"
echo ""
echo ""

echo "Scenario: Verify the error return incase address field is set empty"
echo "Expected: No account for that address" 
echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getaccount\",\"address\":\"RSrtzi1tPkdxD9KfHkXmxDynvPqYc7scV6\"}"

echo ""


