#!/bin/bash

echo ""
echo "
The getrawchangeaddress RPC returns a new Bitcoin address for receiving change. 
This is for use with raw transactions, not normal use."

echo ""

echo "Result: 
A P2PKH address which has not previously been returned by this RPC. 
The address will be removed from the keypool but not marked as a receiving address, 
so RPCs such as the dumpwallet RPC will show it as a change address."

echo ""

curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"getrawchangeaddress\"}"

echo ""

