#!/bin/bash
echo ""
echo "

The getrawtransaction RPC gets a hex-encoded serialized transaction or a JSON object describing the transaction. By default, Bitcoin Core only stores complete transaction data for UTXOs and your own transactions, so the RPC may fail on historic transactions unless you use the non-default txindex=1 in your Bitcoin Core startup settings.

Parameter #1—the TXID of the transaction to get
Parameter #2—whether to get the serialized or decoded transaction
Result (if transaction not found)—null
"

echo ""




curl --url "http://127.0.0.1:7778"  --data "{\"method\":\"getrawtransaction\",\"params\":[\"7173c6a02ed2882ffaf6365cad9ed256bd5a60515658a26ab7ba5fcf4793c3bc\"]}"
echo ""
