#!/bin/bash
echo ""
echo "The gettxout RPC returns details about a transaction output. Only unspent transaction outputs (UTXOs) are guaranteed to be available.

Parameter #1—the TXID of the output to get
Parameter #2—the output index number (vout) of the output to get
Parameter #3—whether to display unconfirmed outputs from the memory "
echo ""

curl --url "http://127.0.0.1:7778"  --data "{\"coin\":\"BTCD\",\"method\":\"gettxout\",\"params\":[\"51ae6e4cef61c9f496ab9df81800afacd1397bebafafb426b3c5eee1d069e84d\", 1]}"
echo ""
