#!/bin/bash
echo ""

echo "

The gettransaction RPC gets detailed information about an in-wallet transaction.

Parameter #1—a transaction identifier (TXID)
Parameter #2—whether to include watch-only addresses in details and calculations
Result—a description of the transaction
"
echo ""

curl --url "http://127.0.0.1:7778"  --data "{\"method\":\"gettransaction\",\"params\":[\"e3c08af74ca337ec632294c78c1deb461944e824f9272a280e4e750e70782714\"]}"
echo ""
