#!/bin/bash

echo ""
echo "The sendtoaddress RPC spends an amount to a given address.

Parameter #1—to address
Parameter #2—amount to spend"
echo ""
echo "Dependencies:"
echo "Walletpassphrase, Incase valid is locked"
echo "getaccountaddress, incase account and address don't exist already"
echo ""
echo "Scenario: Verify that amount is sent to given account"
echo "Results: Amount should be sent to the given account"
echo ""

curl --url "http://127.0.0.1:7778"  --data "{\"method\":\"sendtoaddress\",\"params\":[\"RQbUDfuCitztPgJkG8edBU5dy59GD7WQqT\", 0.0004]}"
echo ""
