#!/bin/bash
clear
echo ""

echo "
The walletpassphrase RPC stores the wallet decryption key in memory for the indicated number of seconds. 
Issuing the walletpassphrase command while the wallet is already unlocked will set a new unlock time 
that overrides the old one.

Parameter #1—the passphrase
Parameter #2—the number of seconds to leave the wallet unlocked

"
echo ""
echo "
Scenario: To Test walletpassphrase with invalid password
Result:   ERORR: Passphrase not found in decrypted json"
echo ""
curl --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"walletpassphrase\",\"password\":\"kashifali\",\"timeout\":300}"
echo ""

