#!/bin/bash

curl -s --url "http://127.0.0.1:7778" --data "{\"agent\":\"bitcoinrpc\",\"method\":\"walletpassphrasechange\",\"oldpassword\":\"Admin123@\",\"newpassword\":\"Admin123456@\",\"oldpermanentfile\":\"\",\"permanentfile\":\"\"}"


