#!/bin/bash

#set -x

CC="$(xcrun --sdk iphoneos --find clang) -isysroot $(xcrun --sdk iphoneos --show-sdk-path)  -arch armv7 -arch arm64 -arch armv7s"

rm ../agents/iguana *.o

if [[ $# -eq 0 ]]; then
    git pull
fi

cd secp256k1; ./m_ios; cd ..

echo CC=$CC

$CC -v -Wno-deprecated -O2 -c -DLIQUIDITY_PROVIDER=1 *.c ../basilisk/basilisk.c ../gecko/gecko.c ../datachain/datachain.c
$CC -v -Wno-deprecated -c -DLIQUIDITY_PROVIDER=1 main.c iguana777.c iguana_bundles.c ../basilisk/basilisk.c

$CC -v -Wno-deprecated -o ../agents/iguana -O2 *.o ../OSlibs/ios/lib/libssl.a ../OSlibs/ios/lib/libcrypto.a ../agents/libcrypto777.a  -L $(xcrun --sdk iphoneos --show-sdk-path)/usr/lib ../OSlibs/ios/lib/libcurl.a -framework Foundation -lz -framework Security -lm 
